name: Trigger Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  call-shared-workflow:
    uses: ciclo-de-vida-II/AUY1104-SharedWorkflows/.github/workflows/deploy-api.yaml@main
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}